from django.contrib import admin
from .models import *

admin.site.register(Reference)
admin.site.register(Project)
admin.site.register(Date)
admin.site.register(Culture)
admin.site.register(Epoch)
admin.site.register(Location)
admin.site.register(Site)
admin.site.register(Profile)
admin.site.register(Layer)
admin.site.register(Sample)
admin.site.register(Person)
admin.site.register(Affiliation)
admin.site.register(Author)
admin.site.register(Image)
admin.site.register(Gallery)
admin.site.register(DatingMethod)
admin.site.register(Synonym)
admin.site.register(Taxon)
admin.site.register(FaunalAssemblage)
admin.site.register(Description)
