# Generated by Django 4.1.1 on 2022-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geo',
            field=models.JSONField(blank=True, null=True, verbose_name='geojson'),
        ),
    ]
