# Generated by Django 4.1.1 on 2022-10-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_location_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tags'),
        ),
    ]
