# Generated by Django 4.1.1 on 2022-10-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reference_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='author'),
        ),
    ]
