# Generated by Django 4.1.1 on 2022-10-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reference_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='link',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='tags',
        ),
        migrations.AddField(
            model_name='reference',
            name='short',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='short'),
        ),
    ]
