# Generated by Django 4.1.1 on 2022-10-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_reference_author_remove_reference_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='profile',
        ),
        migrations.AddField(
            model_name='layer',
            name='profile',
            field=models.ManyToManyField(related_name='layer', to='main.profile', verbose_name='profile'),
        ),
    ]
