# Generated by Django 4.1.1 on 2022-10-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_profile_ref_remove_layer_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['pos']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='main.site', verbose_name='site'),
        ),
    ]
