# Generated by Django 4.1.1 on 2022-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_checkpoint_description_culture_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='site_use',
            field=models.TextField(blank=True, verbose_name='site use'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='date',
            field=models.ManyToManyField(to='main.date', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='date',
            field=models.ManyToManyField(to='main.date', verbose_name='date'),
        ),
    ]
