# Generated by Django 4.1.1 on 2022-10-23 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_layer_site_use_alter_culture_date_alter_epoch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='characteristics',
            field=models.TextField(blank=True, verbose_name='characteristics'),
        ),
        migrations.CreateModel(
            name='MammalianAssemblage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mammals', models.TextField(blank=True, verbose_name='mammals')),
                ('layer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mammalian_assemblage', to='main.layer', verbose_name='layer')),
                ('ref', models.ManyToManyField(blank=True, to='main.reference', verbose_name='reference')),
            ],
        ),
    ]
