# Generated by Django 4.1.1 on 2022-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_layer_characteristics_mammalianassemblage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='tags',
            field=models.TextField(blank=True, verbose_name='tags'),
        ),
    ]
