# Generated by Django 4.1.1 on 2022-10-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_reference_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='hominin_group',
            field=models.CharField(blank=True, max_length=500, verbose_name='hominin_group'),
        ),
    ]
