# Generated by Django 4.1.1 on 2022-10-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_culture_hominin_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culture',
            options={'ordering': ['mean_upper']},
        ),
        migrations.AlterModelOptions(
            name='epoch',
            options={'ordering': ['mean_upper']},
        ),
        migrations.AddField(
            model_name='culture',
            name='mean_lower',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='culture',
            name='mean_upper',
            field=models.IntegerField(blank=True, default=1000000),
        ),
        migrations.AddField(
            model_name='epoch',
            name='mean_lower',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='epoch',
            name='mean_upper',
            field=models.IntegerField(blank=True, default=1000000),
        ),
    ]
