# Generated by Django 4.1.1 on 2022-10-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_culture_options_alter_epoch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='mean_lower',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='layer',
            name='mean_upper',
            field=models.IntegerField(blank=True, default=1000000),
        ),
    ]
