# Generated by Django 4.1.1 on 2022-10-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_layer_mean_lower_layer_mean_upper'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='country',
            field=models.CharField(blank=True, max_length=200, verbose_name='country'),
        ),
    ]
