# Generated by Django 4.1.1 on 2022-10-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_site_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='mean_lower',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='mean_upper',
            field=models.IntegerField(blank=True, default=100000),
        ),
        migrations.AlterField(
            model_name='culture',
            name='mean_upper',
            field=models.IntegerField(blank=True, default=100000),
        ),
    ]
