# Generated by Django 4.1.1 on 2022-10-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_site_options_checkpoint_mean_lower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='main.culture', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='epoch',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='main.epoch', verbose_name='parent'),
        ),
    ]
