# Generated by Django 4.1.1 on 2022-10-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_reference_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='checkpoint',
            field=models.ManyToManyField(blank=True, related_name='layer', to='main.checkpoint', verbose_name='checkpoint'),
        ),
    ]
