# Generated by Django 4.1.1 on 2022-10-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_layer_checkpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('email', models.CharField(max_length=300, verbose_name='email')),
                ('affiliation', models.CharField(blank=True, max_length=300, verbose_name='affiliation')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='site', to='main.contactperson', verbose_name='contact'),
        ),
    ]
