# Generated by Django 4.1.1 on 2022-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_contactperson_site_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='tags',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='tag'),
        ),
    ]
