# Generated by Django 4.1.1 on 2022-11-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_contactperson_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='loc',
        ),
    ]
