# Generated by Django 4.1.1 on 2022-11-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_culture_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='date',
        ),
    ]
