# Generated by Django 4.1.1 on 2022-11-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_culture_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culture',
            options={'ordering': ['upper']},
        ),
        migrations.RenameField(
            model_name='culture',
            old_name='mean_lower',
            new_name='lower',
        ),
        migrations.RenameField(
            model_name='culture',
            old_name='mean_upper',
            new_name='upper',
        ),
    ]
