# Generated by Django 4.1.1 on 2022-11-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_epoch_options_remove_checkpoint_mean_lower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='doi',
            field=models.CharField(max_length=500, verbose_name='doi'),
        ),
    ]
