# Generated by Django 4.1.1 on 2022-11-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_reference_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
    ]
