# Generated by Django 4.1.1 on 2022-11-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_reference_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culture',
            options={'ordering': ['-upper']},
        ),
        migrations.AlterField(
            model_name='culture',
            name='lower',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='upper',
            field=models.IntegerField(blank=True, default=100000, null=True),
        ),
    ]
