# Generated by Django 4.1.1 on 2022-11-18 22:27

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=main.models.Gallery, to='main.gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
