# Generated by Django 4.1.1 on 2022-11-18 22:42

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_site_gallery_alter_gallery_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.TextField(blank=True, null=True, verbose_name='alt'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='gallery_upload/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='site',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=main.models.Gallery, to='main.gallery'),
        ),
    ]
