# Generated by Django 4.1.1 on 2022-11-18 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_gallery_title_alter_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site', to='main.gallery', verbose_name='gallery'),
        ),
    ]
