# Generated by Django 4.1.1 on 2022-11-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_site_new_description_alter_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='description',
        ),
    ]
