# Generated by Django 4.1.1 on 2022-11-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_remove_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_done',
            field=models.BooleanField(default=False, verbose_name='done'),
        ),
    ]
