# Generated by Django 4.1.1 on 2022-12-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_date_estimate_date_plusminus_alter_date_lower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200, verbose_name='option')),
            ],
        ),
    ]
