# Generated by Django 4.1.1 on 2022-12-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_datingmethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datingmethod',
            options={'ordering': ['option']},
        ),
        migrations.RenameField(
            'site',
            'new_description',
            'description'
        ),
        migrations.AlterField(
            model_name='layer',
            name='date',
            field=models.ManyToManyField(blank=True, related_name='model', to='main.date', verbose_name='date'),
        ),
    ]
