# Generated by Django 4.1.1 on 2022-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_datingmethod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='oxa',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='oxa-code'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.JSONField(blank=True, null=True, verbose_name='description'),
        ),
    ]
