# Generated by Django 4.1.1 on 2022-12-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_date_oxa_alter_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='curve',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='calibration_curve'),
        ),
    ]
