# Generated by Django 4.1.1 on 2022-12-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_date_curve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
