# Generated by Django 4.1.1 on 2022-12-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_date_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='unit'),
        ),
    ]
