# Generated by Django 4.1.1 on 2022-12-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_layer_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['short']},
        ),
    ]
