# Generated by Django 4.1.1 on 2022-12-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_layer_reldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointlayerjunction',
            name='Checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='junction', to='main.checkpoint', verbose_name='checkpoint'),
        ),
        migrations.AlterField(
            model_name='checkpointlayerjunction',
            name='Layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='junction', to='main.layer', verbose_name='layer'),
        ),
    ]
