# Generated by Django 4.1.1 on 2022-12-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_checkpointlayerjunction_checkpoint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpointlayerjunction',
            old_name='Checkpoint',
            new_name='checkpoint',
        ),
        migrations.RenameField(
            model_name='checkpointlayerjunction',
            old_name='Layer',
            new_name='layer',
        ),
    ]
