# Generated by Django 4.1.1 on 2022-12-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_rename_checkpoint_checkpointlayerjunction_checkpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('type', models.CharField(blank=True, max_length=300, null=True, verbose_name='type')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='layer', to='main.synonym', verbose_name='synonym'),
        ),
        migrations.AddField(
            model_name='sample',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='sample', to='main.synonym', verbose_name='synonym'),
        ),
        migrations.AddField(
            model_name='site',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='site', to='main.synonym', verbose_name='synonym'),
        ),
    ]
