# Generated by Django 4.1.1 on 2022-12-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_synonym_layer_synonyms_sample_synonyms_site_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='main.layer', verbose_name='parent layer'),
        ),
    ]
