# Generated by Django 4.1.5 on 2023-01-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_rename_parent_culture_culture_alter_layer_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='ref',
            field=models.ManyToManyField(blank=True, related_name='culture', to='main.reference', verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='name'),
        ),
    ]
