# Generated by Django 4.1.5 on 2023-01-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_culture_ref_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='elevation',
            field=models.IntegerField(blank=True, null=True, verbose_name='elevation'),
        ),
    ]
