# Generated by Django 4.1 on 2023-01-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_site_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='tags',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='tags'),
        ),
    ]
