# Generated by Django 4.1 on 2023-01-13 14:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_date_hidden_alter_contactperson_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'default_manager_name': 'visible_objects'},
        ),
        migrations.AlterModelManagers(
            name='date',
            managers=[
                ('visible_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
