# Generated by Django 4.1 on 2023-01-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_image_gallery_alter_relativedate_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='reldate',
        ),
        migrations.AddField(
            model_name='relativedate',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reldate', to='main.layer', verbose_name='layer'),
        ),
    ]
