# Generated by Django 4.1 on 2023-05-02 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0065_faunalassemblage_taxon_delete_mammalianassemblage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="faunalassemblage",
            old_name="mammals",
            new_name="taxa",
        ),
    ]
