# Generated by Django 4.1 on 2023-05-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0066_rename_mammals_faunalassemblage_taxa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faunalassemblage",
            name="layer",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assemblage",
                to="main.layer",
                verbose_name="layer",
            ),
        ),
    ]
