# Generated by Django 4.1 on 2023-05-02 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0067_alter_faunalassemblage_layer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxon",
            options={"ordering": ["family"]},
        ),
    ]
