# Generated by Django 4.1 on 2023-05-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0068_alter_taxon_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faunalassemblage",
            name="layer",
        ),
        migrations.RemoveField(
            model_name="faunalassemblage",
            name="ref",
        ),
        migrations.AddField(
            model_name="faunalassemblage",
            name="layer",
            field=models.ManyToManyField(
                blank=True,
                related_name="assemblage",
                to="main.layer",
                verbose_name="layer",
            ),
        ),
        migrations.AddField(
            model_name="faunalassemblage",
            name="ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.reference",
                verbose_name="reference",
            ),
        ),
    ]
