# Generated by Django 4.1 on 2023-05-02 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0069_remove_faunalassemblage_layer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faunalassemblage",
            name="layer",
        ),
        migrations.RemoveField(
            model_name="faunalassemblage",
            name="ref",
        ),
        migrations.AddField(
            model_name="faunalassemblage",
            name="layer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assemblage",
                to="main.layer",
                verbose_name="layer",
            ),
        ),
        migrations.AddField(
            model_name="faunalassemblage",
            name="ref",
            field=models.ManyToManyField(
                blank=True, to="main.reference", verbose_name="reference"
            ),
        ),
    ]
