# Generated by Django 4.1 on 2023-05-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0071_foundtaxon_alter_faunalassemblage_taxa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faunalassemblage",
            name="taxa",
            field=models.ManyToManyField(to="main.taxon"),
        ),
    ]
