# Generated by Django 4.1 on 2023-08-23 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0073_alter_faunalassemblage_taxa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactperson",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="foundtaxon",
            options={"ordering": ["taxon__family"]},
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.JSONField(blank=True, null=True, verbose_name="content"),
                ),
                (
                    "author",
                    models.ManyToManyField(
                        blank=True,
                        related_name="description",
                        to="main.contactperson",
                        verbose_name="author",
                    ),
                ),
                (
                    "gallery",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="description",
                        to="main.gallery",
                        verbose_name="gallery",
                    ),
                ),
                (
                    "ref",
                    models.ManyToManyField(
                        blank=True,
                        related_name="description",
                        to="main.reference",
                        verbose_name="reference",
                    ),
                ),
            ],
        ),
    ]
