# Generated by Django 4.1 on 2023-08-23 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0076_remove_description_author_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_new",
                to="main.description",
                verbose_name="description_new",
            ),
        ),
        migrations.AlterField(
            model_name="description",
            name="gallery",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="description_old",
                to="main.gallery",
                verbose_name="gallery_old",
            ),
        ),
    ]
