# Generated by Django 4.1 on 2023-08-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0078_remove_description_gallery_alter_gallery_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="description",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="description",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="description",
            name="object_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
