# Generated by Django 4.1 on 2023-08-23 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0079_description_content_type_description_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="description",
        ),
        migrations.RemoveField(
            model_name="site",
            name="gallery",
        ),
        migrations.RemoveField(
            model_name="site",
            name="new_description",
        ),
    ]
