# Generated by Django 4.1 on 2023-08-23 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0081_remove_author_person_alter_description_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
