# Generated by Django 4.1 on 2023-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0084_alter_gallery_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1200, verbose_name="name")),
            ],
        ),
    ]
