# Generated by Django 4.1 on 2023-08-24 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0085_affiliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactperson",
            name="aff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person",
                to="main.affiliation",
                verbose_name="aff",
            ),
        ),
    ]
