# Generated by Django 4.1 on 2023-08-24 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0086_contactperson_aff"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactPerson",
            new_name="Person",
        ),
    ]
