# Generated by Django 4.1 on 2023-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0087_rename_contactperson_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="aff",
        ),
        migrations.AddField(
            model_name="person",
            name="aff",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="person",
                to="main.affiliation",
                verbose_name="aff",
            ),
        ),
    ]
