# Generated by Django 4.1 on 2023-08-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0088_remove_person_aff_person_aff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="aff",
            field=models.ManyToManyField(
                blank=True,
                related_name="person",
                to="main.affiliation",
                verbose_name="aff",
            ),
        ),
    ]
