# Generated by Django 4.1 on 2023-08-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0089_alter_person_aff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affiliation",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="person",
            name="affiliation",
        ),
        migrations.RenameField("person", "aff", "affiliation"),
    ]
