# Generated by Django 4.1 on 2023-08-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0090_alter_affiliation_options_remove_person_aff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="order",
        ),
        migrations.AddField(
            model_name="author",
            name="position",
            field=models.IntegerField(default=1, verbose_name="position"),
        ),
        migrations.AlterField(
            model_name="person",
            name="affiliation",
            field=models.ManyToManyField(
                blank=True,
                related_name="person",
                to="main.affiliation",
                verbose_name="affiliation",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.CharField(
                default="placeholder@fill.me", max_length=300, verbose_name="email"
            ),
        ),
    ]
