# Generated by Django 4.1 on 2023-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0094_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="namespace",
            field=models.CharField(
                blank=True, max_length=300, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="password",
            field=models.TextField(blank=True, null=True, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=500, unique=True, verbose_name="name"),
        ),
    ]
