# Generated by Django 4.1 on 2023-09-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0097_project_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="set_lower",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="layer",
            name="set_upper",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
