# Generated by Django 4.1 on 2023-10-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0099_remove_sample_description_sample_batch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="project",
            field=models.ManyToManyField(
                blank=True,
                related_name="sample",
                to="main.project",
                verbose_name="project",
            ),
        ),
    ]
