# Generated by Django 4.1 on 2023-10-05 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0101_alter_sample_options_rename_parent_site_site"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layer",
            old_name="parent",
            new_name="layer",
        ),
    ]
