# Generated by Django 4.1 on 2023-10-11 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0103_remove_culture_description_culture_description_old"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="culture",
            name="description_old",
        ),
    ]
