# Generated by Django 4.1 on 2023-10-31 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0106_alter_sample_layer"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sample",
                to="main.site",
                verbose_name="site",
            ),
        ),
    ]
