# Generated by Django 4.1 on 2023-11-01 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0107_sample_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="name"
                    ),
                ),
                (
                    "sampled_by",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="sampled_by"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sample_batch",
                        to="main.site",
                        verbose_name="site",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="sample",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sample",
                to="main.samplebatch",
                verbose_name="sample_batch",
            ),
        ),
    ]
