# Generated by Django 4.1 on 2023-11-01 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0109_samplebatch_year_of_arrival"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relativedate",
            name="layer",
        ),
        migrations.RemoveField(
            model_name="relativedate",
            name="ref",
        ),
        migrations.RemoveField(
            model_name="relativedate",
            name="relation",
        ),
        migrations.DeleteModel(
            name="CheckpointLayerJunction",
        ),
        migrations.DeleteModel(
            name="RelativeDate",
        ),
    ]
