# Generated by Django 4.1 on 2023-11-01 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0110_remove_relativedate_layer_remove_relativedate_ref_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="checkpoint",
        ),
        migrations.DeleteModel(
            name="Checkpoint",
        ),
    ]
