# Generated by Django 4.1 on 2023-11-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0111_remove_layer_checkpoint_delete_checkpoint"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyzedSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("library", models.CharField(max_length=200, verbose_name="library")),
                (
                    "seqrun",
                    models.CharField(max_length=400, verbose_name="sequencing run"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, null=True, verbose_name="metadata"),
                ),
                ("project", models.ManyToManyField(blank=True, to="main.project")),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyzed_sample",
                        to="main.sample",
                    ),
                ),
            ],
            options={
                "unique_together": {("library", "seqrun")},
            },
        ),
    ]
