# Generated by Django 4.1 on 2023-11-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0112_analyzedsample"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzedsample",
            name="probes",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="probes"
            ),
        ),
    ]
