# Generated by Django 4.1 on 2023-11-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0113_analyzedsample_probes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyzedsample",
            name="project",
            field=models.ManyToManyField(
                blank=True,
                related_name="analyzed_sample",
                to="main.project",
                verbose_name="project",
            ),
        ),
    ]
