# Generated by Django 4.1 on 2023-11-10 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0115_alter_analyzedsample_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={"ordering": ["layer__site", "layer__pos", "name"]},
        ),
    ]
