# Generated by Django 4.1 on 2023-11-10 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0116_alter_sample_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={"ordering": ["site", "batch", "layer__pos", "name"]},
        ),
    ]
