# Generated by Django 4.1 on 2023-11-10 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0117_alter_sample_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyzedsample",
            options={"ordering": ["sample__site", "sample__layer", "sample", "probes"]},
        ),
    ]
