# Generated by Django 4.1 on 2024-01-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0118_alter_analyzedsample_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="orcid",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="orcid_id"
            ),
        ),
    ]
