# Generated by Django 4.1 on 2024-03-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0121_site_connections"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="epoch",
            options={"ordering": ["upper"]},
        ),
        migrations.RemoveField(
            model_name="epoch",
            name="date",
        ),
        migrations.RemoveField(
            model_name="epoch",
            name="description",
        ),
        migrations.RemoveField(
            model_name="epoch",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="epoch",
            name="ref",
        ),
        migrations.AddField(
            model_name="epoch",
            name="lower",
            field=models.IntegerField(blank=True, null=True, verbose_name="lower"),
        ),
        migrations.AddField(
            model_name="epoch",
            name="upper",
            field=models.IntegerField(blank=True, null=True, verbose_name="upper"),
        ),
    ]
