# Generated by Django 4.1 on 2024-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0122_alter_epoch_options_remove_epoch_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="date",
            field=models.ManyToManyField(
                blank=True,
                related_name="origin_model",
                to="main.date",
                verbose_name="date",
            ),
        ),
    ]
