# Generated by Django 4.1 on 2024-03-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0123_alter_layer_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxon",
            options={},
        ),
        migrations.RemoveField(
            model_name="taxon",
            name="common_name",
        ),
        migrations.AddField(
            model_name="faunalassemblage",
            name="method",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Method"
            ),
        ),
        migrations.AddField(
            model_name="taxon",
            name="analysis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faunal_results",
                to="main.faunalassemblage",
            ),
        ),
        migrations.AddField(
            model_name="taxon",
            name="results",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Faunal Results"
            ),
        ),
        migrations.AddField(
            model_name="taxon",
            name="taxid",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="TaxID"
            ),
        ),
    ]
