# Generated by Django 4.1 on 2024-03-28 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0127_alter_faunalanalysis_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FaunalAnalysis",
            new_name="LayerAnalysis",
        ),
    ]
