# Generated by Django 4.1 on 2024-04-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0129_alter_layeranalysis_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layeranalysis",
            name="layer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="layer_analysis",
                to="main.layer",
                verbose_name="layer",
            ),
        ),
    ]
