# Generated by Django 4.1 on 2024-04-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0130_alter_layeranalysis_layer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layeranalysis",
            name="ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.reference",
                verbose_name="reference",
            ),
        ),
    ]
