# Generated by Django 4.1 on 2024-04-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0131_alter_layeranalysis_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="layeranalysis",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layer_analysis",
                to="main.site",
            ),
        ),
    ]
