# Generated by Django 4.1 on 2024-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0132_layeranalysis_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="date",
            name="sigma",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="sigma/CI"
            ),
        ),
    ]
