# Generated by Django 4.1 on 2024-06-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0135_layer_date_lower_layer_date_upper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="date_lower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="layer_lower_date",
                to="main.date",
                verbose_name="lower date",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="date_upper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="layer_upper_date",
                to="main.date",
                verbose_name="upper date",
            ),
        ),
    ]
