# Generated by Django 4.1 on 2024-06-17 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0136_alter_layer_date_lower_alter_layer_date_upper"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="date_lower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sample_lower_date",
                to="main.date",
                verbose_name="lower date",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="date_upper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sample_upper_date",
                to="main.date",
                verbose_name="upper date",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="date",
            field=models.ManyToManyField(
                blank=True, related_name="sample", to="main.date", verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="mean_lower",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="sample",
            name="mean_upper",
            field=models.IntegerField(blank=True, default=1000000),
        ),
    ]
