# Generated by Django 4.1 on 2024-06-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0137_sample_date_lower_sample_date_upper_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="date",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_date",
                to="main.date",
                verbose_name="date",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="date_lower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_lower_date",
                to="main.date",
                verbose_name="lower date",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="date_upper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_upper_date",
                to="main.date",
                verbose_name="upper date",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="date",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_date",
                to="main.date",
                verbose_name="date",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="date_lower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_lower_date",
                to="main.date",
                verbose_name="lower date",
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="date_upper",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_upper_date",
                to="main.date",
                verbose_name="upper date",
            ),
        ),
    ]
