# Generated by Django 4.1 on 2024-06-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0139_layeranalysis_culture_alter_layer_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="mean_lower",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="layer",
            name="mean_upper",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="mean_lower",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="mean_upper",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
