# Generated by Django 4.1 on 2024-07-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0142_analyzedsample_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyzedsample",
            name="qc_pass",
            field=models.BooleanField(default=True, verbose_name="qc_pass"),
        ),
    ]
