# Generated by Django 4.1 on 2024-07-03 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0143_analyzedsample_qc_pass"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyzedsample",
            options={
                "ordering": [
                    "sample__site",
                    "sample__layer",
                    "sample",
                    "seqrun",
                    "probes",
                ]
            },
        ),
    ]
