# Generated by Django 4.1 on 2024-07-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0144_alter_analyzedsample_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layeranalysis",
            name="ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="layer_analysis",
                to="main.reference",
                verbose_name="reference",
            ),
        ),
    ]
