# Generated by Django 4.1 on 2024-07-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0145_alter_layeranalysis_ref"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Type"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Taxonomy Data"
                    ),
                ),
            ],
        ),
    ]
