# Generated by Django 4.1 on 2024-07-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0146_taxonomy"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ref",
            field=models.ManyToManyField(
                blank=True,
                related_name="project",
                to="main.reference",
                verbose_name="reference",
            ),
        ),
    ]
