# Generated by Django 4.1 on 2024-08-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0148_analyzedsample_lane"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="analyzedsample",
            unique_together={("library", "seqrun", "lane")},
        ),
        migrations.AddField(
            model_name="analyzedsample",
            name="seqpool",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="seqpool"
            ),
        ),
    ]
