# Generated by Django 4.1 on 2024-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0149_alter_analyzedsample_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedsample',
            name='enc_batch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ENC Batch'),
        ),
        migrations.AddField(
            model_name='analyzedsample',
            name='lnc_batch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='LNC Batch'),
        ),
        migrations.AddField(
            model_name='analyzedsample',
            name='lysate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lysate Id'),
        ),
    ]
