# Generated by Django 4.1 on 2024-09-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0149_alter_analyzedsample_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedsample',
            name='negative_control_batch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Negative Control Batch'),
        ),
        migrations.AddField(
            model_name='sample',
            name='negative_control_batch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Negative Control Batch'),
        ),
        migrations.AlterField(
            model_name='analyzedsample',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyzed_sample', to='main.sample'),
        ),
    ]
