# Generated by Django 4.1 on 2024-09-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0150_analyzedsample_enc_batch_analyzedsample_lnc_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedsample',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analyzed_sample', to='main.sample'),
        ),
    ]
