# Generated by Django 4.1 on 2024-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0151_alter_analyzedsample_sample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzedsample',
            options={'ordering': ['seqrun', 'library']},
        ),
        migrations.AlterModelOptions(
            name='quicksandanalysis',
            options={'ordering': ['analyzedsample__sample__site', 'analyzedsample__sample__layer', 'analyzedsample__sample', 'analyzedsample__seqrun', 'analyzedsample__probes']},
        ),
        migrations.AddField(
            model_name='analyzedsample',
            name='capture',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='capture'),
        ),
        migrations.AlterField(
            model_name='analyzedsample',
            name='library',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='library'),
        ),
    ]
