# Generated by Django 4.1 on 2024-11-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0152_alter_analyzedsample_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedsample',
            name='efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='Library Prep Efficiency'),
        ),
        migrations.AddField(
            model_name='analyzedsample',
            name='molecules_qpcr',
            field=models.IntegerField(blank=True, null=True, verbose_name='qPCR molecules'),
        ),
    ]
