# Generated by Django 5.1.3 on 2025-01-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0155_reference_bibtex'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='exclude_from_print',
            field=models.BooleanField(default=False, verbose_name='exclude_from_print'),
        ),
    ]
