# Generated by Django 5.1.3 on 2025-04-09 08:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0157_layer_colour_layer_colour_hex_layer_colour_munsell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='unit',
        ),
        migrations.AlterField(
            model_name='layer',
            name='colour_munsell',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Munsell Number in the format 8.75YR 4.5/3', regex='^[0-9]+(\\.[0-9]+)?[A-Z]+\\s+[1-9](\\.[0-9]+)?/[0-9]+(\\.[0-9]+)?$')], verbose_name='colour_munsell'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='texture',
            field=models.CharField(blank=True, choices=[('', ''), ('Clay', 'Clay'), ('Clay Loam', 'Clay Loam'), ('Sandy Clay', 'Sandy Clay'), ('Sandy Clay Loam', 'Sandy Clay Loam'), ('Sandy Loam', 'Sandy Loam'), ('Sand/Silt', 'Sand/Silt'), ('Loam', 'Loam'), ('Loamy Sand', 'Loamy Sand'), ('Sand', 'Sand'), ('Silty Clay', 'Silty Clay'), ('Silty Clay Loam', 'Silty Clay Loam'), ('Silt Loam', 'Silt Loam'), ('Silt', 'Silt')], max_length=200, null=True, verbose_name='texture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main.site', verbose_name='site'),
        ),
        migrations.CreateModel(
            name='ProfileLayerJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_junction', to='main.layer', verbose_name='layer')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_junction', to='main.profile', verbose_name='profile')),
            ],
        ),
    ]
