# Generated by Django 5.1.3 on 2025-04-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0159_alter_layer_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelayerjunction',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_junction', to='main.layer', verbose_name='layer'),
        ),
        migrations.AlterField(
            model_name='profilelayerjunction',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layer_junction', to='main.profile', verbose_name='profile'),
        ),
    ]
