# Generated by Django 5.1.3 on 2025-04-09 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0161_alter_layer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilelayerjunction',
            options={'ordering': ['profile', 'position']},
        ),
    ]
