# Generated by Django 5.1.3 on 2025-04-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0162_alter_profilelayerjunction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='additional_cultures',
            field=models.ManyToManyField(blank=True, related_name='layers', to='main.culture', verbose_name='additional_cultures'),
        ),
    ]
