# Generated by Django 5.1.3 on 2025-04-11 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0163_layer_additional_cultures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['profile_junction__position']},
        ),
        migrations.CreateModel(
            name='AffiliationPersonJunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_junction', to='main.affiliation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliation_junction', to='main.person')),
            ],
        ),
    ]
