# Generated by Django 5.1.3 on 2025-04-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0164_alter_layer_options_affiliationpersonjunction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliationpersonjunction',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='affiliation',
        ),
    ]
