# Generated by Django 5.1.3 on 2025-04-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0166_sample_domain_sample_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='hominin_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='hominin_group'),
        ),
    ]
