# Generated by Django 5.1.3 on 2025-04-16 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0167_sample_hominin_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='main.sample', verbose_name='parent'),
        ),
    ]
