# Generated by Django 5.1.3 on 2025-05-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0168_alter_sample_sample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['site', 'batch', 'layer', 'sample__layer', 'name']},
        ),
        migrations.AddField(
            model_name='project',
            name='year_of_publication',
            field=models.IntegerField(blank=True, null=True, verbose_name='year_of_publication'),
        ),
    ]
