# Generated by Django 5.1.3 on 2025-06-17 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0169_alter_sample_options_project_year_of_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
        migrations.AddField(
            model_name='profilelayerjunction',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
    ]
