# Generated by Django 5.1.3 on 2025-07-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0170_profile_visible_profilelayerjunction_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='sample',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='note'),
        ),
    ]
