# Generated by Django 5.1.3 on 2025-07-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0172_probetranslationtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parameters',
            field=models.JSONField(blank=True, null=True, verbose_name='parameters'),
        ),
    ]
