# Generated by Django 5.1.3 on 2025-09-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0173_project_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(max_length=64)),
                ('colour_munsell', models.CharField(max_length=32)),
            ],
        ),
    ]
