# Generated by Django 5.1.3 on 2025-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0173_project_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedsample',
            name='reamp_library',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='library'),
        ),
    ]
