# Generated by Django 5.1.3 on 2025-12-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0174_analyzedsample_reamp_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='parsedHTML',
            field=models.TextField(blank=True, verbose_name='parsedHTML'),
        ),
    ]
