# Generated by Django 5.1.3 on 2025-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0174_colours'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourMunsell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_munsell', models.CharField(max_length=32)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ColourName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Colours',
        ),
        migrations.AddField(
            model_name='colourmunsell',
            name='colour_name',
            field=models.ManyToManyField(related_name='munsell_value', to='main.colourname'),
        ),
    ]
