# Generated by Django 5.1.3 on 2025-12-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0175_reference_parsedhtml'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='parsedInline',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='parsedInline'),
        ),
    ]
