# Generated by Django 5.1.3 on 2025-09-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0175_colourmunsell_colourname_delete_colours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='colour_hex',
        ),
        migrations.AlterField(
            model_name='layer',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colour', to='main.colourname'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='colour_munsell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='munsell', to='main.colourmunsell'),
        ),
    ]
