# Generated by Django 5.1.3 on 2025-09-26 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0176_remove_layer_colour_hex_alter_layer_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='colour',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='colour'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='colour_munsell',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid Munsell Number in the format 8.75YR 4.5/3', regex='^[0-9]+(\\.[0-9]+)?[A-Z]+\\s+[1-9](\\.[0-9]+)?/[0-9]+(\\.[0-9]+)?$')], verbose_name='colour_munsell'),
        ),
    ]
