# Generated by Django 5.1.3 on 2026-01-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0176_reference_parsedinline'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedsample',
            name='ena_accession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ENA Accession Id'),
        ),
    ]
