# Generated by Django 5.1.3 on 2026-01-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0177_analyzedsample_ena_accession'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ena_accession',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ENA Accession Id'),
        ),
    ]
