# Generated by Django 5.1.3 on 2025-09-29 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0178_alter_layer_colour_alter_layer_colour_munsell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colour', to='main.colourname'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='colour_munsell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='munsell', to='main.colourmunsell'),
        ),
    ]
