# Generated by Django 5.1.3 on 2026-01-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0178_project_ena_accession'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='annual_mean_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='annual_mean_temp'),
        ),
        migrations.AddField(
            model_name='site',
            name='annual_precipitation_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='annual_precipitation_summ'),
        ),
    ]
