# Generated by Django 5.1.3 on 2025-09-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0179_alter_layer_colour_alter_layer_colour_munsell'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TextureKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.CharField(max_length=64)),
                ('texture_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texture_category', to='main.texturecategory')),
            ],
        ),
    ]
