# Generated by Django 5.1.3 on 2026-01-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0179_site_annual_mean_temp_site_annual_precipitation_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='climate_class',
            field=models.CharField(blank=True, max_length=200, verbose_name='climate_class'),
        ),
        migrations.AlterField(
            model_name='site',
            name='annual_precipitation_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='annual_precipitation_sum'),
        ),
    ]
