# Generated by Django 5.1.3 on 2026-03-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0180_site_climate_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='n_tools',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tools'),
        ),
    ]
