# Generated by Django 5.1.3 on 2026-03-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0181_layer_n_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedsample',
            name='ena_genbank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Genbank'),
        ),
    ]
