# Generated by Django 5.1.3 on 2026-09-27 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0183_project_ena_genbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='NedflowAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Version')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('analyzedsample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nedflow_analysis', to='main.analyzedsample', verbose_name='analyzedsample')),
            ],
            options={
                'ordering': ['analyzedsample__sample__site', 'analyzedsample__sample__layer', 'analyzedsample__sample', 'analyzedsample__seqrun', 'analyzedsample__probes'],
            },
        ),
    ]
